# Generated by Django 3.1.2 on 2020-11-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('neighborhood', models.CharField(max_length=70)),
                ('reference_point', models.CharField(max_length=250)),
            ],
        ),
    ]
